# fly.toml app configuration file generated for eureka-search on 2023-10-05T23:22:51-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "eureka-search"
primary_region = "lax"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
